#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_REGULATOR_REGULATOR_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_REGULATOR_REGULATOR_H_

#define REGULATOR_ENABLE_ACTIVE_LOW (0)
#define REGULATOR_ENABLE_ACTIVE_HIGH (1)

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_REGULATOR_REGULATOR_H_ */
